name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref_type != 'tag' }}

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore Veritas.sln -p:TargetFramework=net8.0
      - name: Build
        run: dotnet build Veritas.sln --configuration Release -p:TargetFramework=net8.0 --no-restore
      - name: Pack
        run: dotnet pack src/Veritas/Veritas.csproj --configuration Release -p:TargetFramework=net8.0 --no-restore --output ./NuGet
      - name: Test
        run: |
          dotnet test test/Veritas.Tests/Veritas.Tests.csproj --configuration Release --no-build \
            --logger "trx;LogFileName=$(AssemblyName)-results.trx" \
            --results-directory ./TestResults \
            --collect:"XPlat Code Coverage"
      - name: Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: 'TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline_AzurePipelines;MarkdownSummaryGitHub;Badges'
          tag: '${{ github.run_number }}'
      - name: Append coverage to job summary
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/*.trx'
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./TestResults/**/coverage.cobertura.xml
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport
      - name: Upload NuGet package
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: ./NuGet/*.nupkg
