name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore Veritas.sln -p:TargetFramework=net8.0
      - name: Build
        run: dotnet build Veritas.sln --configuration Release -p:TargetFramework=net8.0 --no-restore
      - name: Test
        run: dotnet test test/Veritas.Tests/Veritas.Tests.csproj --configuration Release --no-build
