name: docs

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: install docfx
        run: dotnet tool update -g docfx

      - name: build docs
        run: docfx docfx/docfx.json

      - name: publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docfx/_site
